-- MySQL Script generated by MySQL Workbench
-- Sun Jun  2 16:46:47 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema vaiovaio
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `vaiovaio` ;

-- -----------------------------------------------------
-- Schema vaiovaio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vaiovaio` DEFAULT CHARACTER SET latin1 ;
USE `vaiovaio` ;

-- -----------------------------------------------------
-- Table `vaiovaio`.`noticias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vaiovaio`.`noticias` ;

CREATE TABLE IF NOT EXISTS `vaiovaio`.`noticias` (
  `Titulo` VARCHAR(200) NULL DEFAULT NULL,
  `Encabezado` VARCHAR(200) NULL DEFAULT NULL,
  `Cuerpo` VARCHAR(250) NULL DEFAULT NULL,
  `Estado` VARCHAR(45) NULL DEFAULT NULL,
  `idNoticiero` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`idNoticiero`))
ENGINE = MyISAM
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `vaiovaio`.`noticias`
-- -----------------------------------------------------
START TRANSACTION;
USE `vaiovaio`;
INSERT INTO `vaiovaio`.`noticias` (`Titulo`, `Encabezado`, `Cuerpo`, `Estado`, `idNoticiero`) VALUES ('CGE emite nuevo balance tras tromba en Concepción y Talcahuano', '600 empalmes y 90 postes afectados', 'Mediante un comunicado de prensa  la firma detalló que 90 postes resultaron afectados por el paso del inusual fenómeno meteorológico 50 de baja tensión y 40 de media tensión', 'por leer', 1);
INSERT INTO `vaiovaio`.`noticias` (`Titulo`, `Encabezado`, `Cuerpo`, `Estado`, `idNoticiero`) VALUES ('Irma Grese las sádicas ejecuciones de quien fue conocida como la Hiena de Auschwitz', 'La Segunda Guerra Mundial a menudo nos sorprende con sus historias fuera del campo de batalla. Si bien son conocidos', 'Grese quedó en el recuerdo como una de las guardianas más sádicas del principal campo de concentración Nazi. Los hechos fueron relatados por algunas de sus víctimas en el juicio de Belsen, tras el cual fue sentenciada a muerte en 1945', 'por leer', 2);
INSERT INTO `vaiovaio`.`noticias` (`Titulo`, `Encabezado`, `Cuerpo`, `Estado`, `idNoticiero`) VALUES ('El mensaje de Valdivia tras empate entre La Roja y Colo Colo', 'Este sábado se realizó un encuentro amistoso entre la selección chilena que se está preparando para la Copa América de Brasil 2019 y Colo Colo', 'Tras el partido el volante subió una imagen con varios históricos de La Roja junto al mensaje El tiempo pasa y las verdaderas amistades perduran', 'Leido', 3);

COMMIT;

